name: submission_idcamp_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  fl_chart: ^0.69.0
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  lottie: ^3.1.3
  path_provider: ^2.1.5
  sqflite: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
